name: teddyBear
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: "^3.9.0"

dependencies:
  flutter:
    sdk: flutter

  # Routing
  go_router: ^17.0.0

  # HTTP
  http: ^1.5.0

  # dotenv
  flutter_dotenv: ^6.0.0
  # access location
  path_provider: ^2.1.5
  # bloc & dependency injection
  flutter_bloc: ^9.1.1
  get_it: ^9.0.5

  # hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UI / Animations / Icons
  animated_text_kit: ^4.3.0
  iconsax_flutter: ^1.0.1
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0

  # Model / Equality / JSON
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  uuid: ^4.5.2
  analyzer: ^9.0.0

  # google login
  google_sign_in: ^7.2.0
#  get: ^4.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # JSON serialization
  json_serializable: ^6.11.1
  build_runner: ^2.10.1

  # Build-time tools (DEV ONLY)
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/app_icon.png
  adaptive_icon_background: "#F5E2B8"
  adaptive_icon_foreground: assets/icons/app_icon.png

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/native_splash/
    - assets/images/splash/
    - assets/.env
    - assets/prompts/
    - assets/prompts/quotes/
